### ISSUE TITLE
OSError: Index size is not a multiple of vector size. Ensure you are opening using the same metric you used to create the index.: No error (0)

### ISSUE THREAD

**Issue by douscare** [shobhit9618/celeb_recognition#1]
Index size is not a multiple of vector size. Ensure you are opening using the same metric you used to create the index.: No error (0)
Traceback (most recent call last):
  File "C:\CelebDetector\test.py", line 4, in <module>
    celeb_detector.celeb_recognition(img_path)
  File "C:\CelebDetector\venv\lib\site-packages\celeb_detector\celeb_recognition.py", line 37, in celeb_recognition
    pred, img_out = get_celeb_prediction(img, ann_filepath, celeb_mapping_path)
  File "C:\CelebDetector\venv\lib\site-packages\celeb_detector\celeb_utils.py", line 85, in get_celeb_prediction
    _ = ann_index.load(ann_filepath)
OSError: Index size is not a multiple of vector size. Ensure you are opening using the same metric you used to create the index.: No error (0)

**Comment by shobhit9618** [comment]
Hi,
Sorry for the late reply.
What ann_file are you using?

**Comment by samrat213** [comment]
i am directly installing celeb-detector using pip and getting same error

**Comment by shobhit9618** [comment]
You are unable to install celeb-detector using pip?
Which device are you trying it on?

**Comment by rleaver152** [comment]
I have the same issue,  I trained successfully and created an ann_file,   but celeb_recognition.py fails to read it.   The offending line is as reported
```
File "C:\CelebDetector\venv\lib\site-packages\celeb_detector\celeb_utils.py", line 85, in get_celeb_prediction
_ = ann_index.load(ann_filepath)
```

Running under python 3.7      All requirements successfully installed.  Check my MTCNN installation separately and that's working fine.   Appreciate any insight.
